apiVersion: v1
kind: ConfigMap
metadata:
  name: amazon-clone-config
  namespace: amazon-clone
data:
  POSTGRES_DB: amazon_clone
  POSTGRES_USER: amazon
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  MAIL_FROM: noreply@shop.pa1.tech
  MAIL_SERVER: smtp-relay.brevo.com
  MAIL_PORT: "587"
